const cssClasses = {
    base: 'outline-none leading-normal block',
    timepicker: 'p-2 px-4 select-none z-20 mt-1 bg-white rounded border border-gray-400 shadow',
    backdrop: 'fixed w-full h-full top-0 left-0 z-10 md:bg-white md:opacity-0 bg-black opacity-75',
    sizeXs: 'w-32',
    sizeSm: 'w-40',
    sizeMd: 'w-48',
    sizeLg: 'w-56',
    formattedValueXs: 'py-0',
    formattedValueSm: 'py-0',
    formattedValueMd: 'py-1',
    formattedValueLg: 'py-2',
    clear: 'flex items-center justify-center cursor-pointer h-full text-gray-500 hover:text-gray-600',
    clearXs: 'w-4',
    clearSm: 'w-5',
    clearMd: 'w-6',
    clearLg: 'w-8',
    placeholderWrapper: 'border rounded flex flex-no-wrap items-center cursor-pointer hover:border-gray-500',
    placeholderWrapperXs: 'h-6 text-xs',
    placeholderWrapperSm: 'h-6 text-sm',
    placeholderWrapperMd: 'h-8 text-base',
    placeholderWrapperLg: 'h-10 text-lg',
    placeholderValueWrapper: 'flex-1 appearance-none outline-none flex flex-no-wrap items-center',
    caret: 'flex items-center justify-center border-l h-full',
    caretXs: 'w-5',
    caretSm: 'w-6',
    caretMd: 'w-8',
    caretLg: 'w-10',
    timeSeparator: 'px-2 font-bold text-lg text-gray-500',
    hoursMinutesSecondsSelector: 'flex flex-col font-bold',
    hmsSelectorXs: 'px-0 text-sm',
    hmsSelectorSm: 'px-1 text-base',
    hmsSelectorMd: 'px-2 text-lg',
    hmsSelectorLg: 'px-3 text-xl',
    upDownIcons: 'text-gray-500 text-center hover:text-gray-800 hover:cursor-pointer',
    meridiemSelector: 'inline-block border rounded outline-none select-none font-bold text-right ' +
        'p-1 w-10 tracking-widest hover:bg-gray-200 hover:cursor-pointer',
};

export default cssClasses;
