const cssClasses = {
    base: 'outline-none block',
    backdrop: 'fixed w-full h-full top-0 left-0 z-10 md:bg-white md:opacity-0 bg-black opacity-75',
    menu:'block z-20',
    select: 'hidden',
    clear: 'float-right flex-grow-0 flex items-center cursor-pointer w-6 text-gray-500',
    searchClear: 'absolute top-0 right-0 py-2 cursor-pointer w-8 text-gray-500',
    wrapper: 'border rounded flex flex-no-wrap items-center cursor-pointer hover:border-gray-500',
    placeholderWrapper: 'flex-1 outline-none flex flex-no-wrap items-center',
    placeholderWrapperXs: 'text-xs',
    placeholderWrapperSm: 'text-sm',
    placeholderWrapperMd: 'text-base',
    placeholderWrapperLg: 'text-lg',
    placeholder: 'px-2 text-gray-600',
    displayValuePlaceholder: 'px-2',
    remainingValuePlaceholder: 'text-gray-600',
    dropdownWrapper: 'flex-grow-0 border-l h-full px-2',
    dropdownContent: 'bg-white rounded border border-gray-400 shadow',
    dropdownContentItemWrapper: 'left-0 overflow-y-scroll z-20',
    dropdownItem: 'text-gray-800 block relative',
    dropdownItemHover: 'hover:bg-gray-200 hover:cursor-pointer',
    dropdownItemXs: 'leading-tight',
    dropdownItemSm: 'leading-snug',
    dropdownItemMd: 'leading-normal',
    dropdownItemLg: 'leading-relaxed',
    caret: 'flex-grow-0 border-l h-full px-2 text-center',
    caretXs: 'py-0',
    caretSm: 'py-0',
    caretMd: 'py-1',
    caretLg: 'py-2 w-10',
    checkbox: 'w-full h-full py-1 px-4',
};

export default cssClasses;
