const cssClasses = {
    base: 'outline-none block',
    backdrop: 'fixed w-full h-full top-0 left-0 z-10 md:bg-white md:opacity-0 bg-black opacity-75',
    menu:'block z-20',
    select: 'hidden',
    clear: 'float-right grow-0 flex items-center cursor-pointer w-6 text-gray-500',
    searchClear: 'absolute top-0 right-0 py-2 cursor-pointer w-8 text-gray-500',
    wrapper: 'border rounded flex flex-nowrap items-center cursor-pointer border-gray-400 hover:border-gray-500',
    placeholderWrapper: 'flex-1 outline-none flex flex-nowrap items-center',
    placeholderWrapperXs: 'text-xs',
    placeholderWrapperSm: 'text-sm',
    placeholderWrapperMd: 'text-base',
    placeholderWrapperLg: 'text-lg',
    placeholder: 'px-2 text-gray-600',
    displayValuePlaceholder: 'px-2',
    dropdownContent: 'bg-white rounded border border-gray-400 shadow',
    dropdownContentItemWrapper: 'left-0 overflow-y-scroll z-20',
    dropdownItem: 'text-gray-800 block relative',
    dropdownItemHover: 'hover:bg-gray-100 hover:cursor-pointer',
    dropdownItemSelected: 'bg-gray-200',
    dropdownItemXs: 'leading-tight',
    dropdownItemSm: 'leading-snug',
    dropdownItemMd: 'leading-normal',
    dropdownItemLg: 'leading-relaxed',
    caret: 'grow-0 border-l border-gray-300 h-full px-2 text-center',
    caretXs: 'py-0',
    caretSm: 'py-0',
    caretMd: 'py-1',
    caretLg: 'py-2 w-10',
    item: 'w-full h-full py-2 px-4',
    group: 'w-full h-full py-2 px-3 bg-gray-200 text-gray-600 hover:cursor-default',
    groupItem: 'w-full h-full py-2 px-6',
};

export default cssClasses;
